### ISSUE TITLE
 SSO client unable to set cookie

### ISSUE THREAD

**Issue by felischmi2003** [cubiclesoft/sso-client-php#2] opened 2022-02-17 20:44 UTC
`SSO client unable to set cookie '_rid'. Error: Headers already sent. This means HTML or other data (e.g. UTF-8 byte order marker) has been output, which caused HTTP headers to be sent prematurely. Contact the system/website administrator to correct this issue.`

Please Help

**Comment by cubiclesoft** [comment] 2022-02-18 00:36
It means your PHP code sent output before you called the SSO client functions that generally update browser cookies.

Headers are sent before content in HTTP requests.

Closing as this is not a bug.  Support requests are better handled on the Discord chat.

**Closed as completed by cubiclesoft** 2022-02-18 00:36 UTC
